name: Healthz Packer Build Machine image

on:
  push:
    branches:
        - main

env:
  PACKER_VERSION: "1.12.0"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Check the Repo
      uses: actions/checkout@v3

    - name: Installing Postgres 
      run: |
        sudo apt update 
        sudo apt install -y postgresql postgresql-contrib
    
    - name: Installing node_modules
      run: npm install
        
    - name: Starting postgres Service
      run: sudo systemctl start postgresql

    - name: Database and user setup
      run: |
        sudo -u postgres psql -c "CREATE ROLE $DB_USERNAME WITH LOGIN CREATEDB PASSWORD '$DB_PASSWORD';"
        sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USERNAME;"

    - name: dropping the table 
      run: |
          sudo -u postgres psql -d $DB_NAME -c 'DROP TABLE IF EXISTS "HealthChecks" CASCADE;'

    - name: healthz api integration test
      run: npm test

    - name: post job clean up
      if: always()
      run: |
        echo "started cleaning"
        pkill -P $$ || true  
        sudo systemctl stop postgresql  
        echo "done with cleaning"

  packer-mi-generation:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check the Repo
        uses: actions/checkout@v4

      - name: Zipping Application
        run: zip -r webapp.zip .
        working-directory: .
    
      - name: List artifact contents
        run: ls -la webapp.zip
    
      - name: AWS profile configuration
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: Run packer init
        working-directory: packer
        run: packer init .

      - name: Run packer validate
        working-directory: packer
        run: packer validate .

      - name: Authenticate Cred for GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_KEY_GCP }}

      - name: GCP SDK setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta,gsutil'

      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.SERVICE_KEY_GCP}}' > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV
        shell: bash
      
      - name: Build AMI with Packer for both GCP and AWS
        working-directory: packer
        if: success()
        run: |
          packer build --force \
            -var "zip-path=$(pwd)/../webapp.zip" \
            -var "aws-profile=${{ secrets.AWS_PROFILE }}" \
            -var "aws-region=${{ secrets.AWS_REGION }}" \
            -var "aws-instance-type=t3.micro" \
            -var "aws-ssh-username=ubuntu" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "db_user=${{ secrets.DB_USERNAME }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "port=${{ secrets.PORT }}" \
            -var "db_host=${{ secrets.DB_HOST }}" \
            -var "db_port=${{ secrets.DB_PORT }}" \
            -var "aws-subnet-id=${{ secrets.AWS_SUBNET_ID }}" \
            -var "gcp-project-id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "gcp-zone=${{ secrets.GCP_ZONE }}" \
            .



     